#!/bin/bash
# 🚀 QUICK START - Comandos más importantes

echo "=== RAG Memoria Externa IA ==="
echo ""
echo "📋 PRIMEROS PASOS:"
echo "1. npm install              # Instala dependencias"
echo "2. Edita .env.local         # Con tu DATABASE_URL y GOOGLE_API_KEY"
echo "3. npm run db:push          # Crea tabla en BD"
echo "4. npm run ingest           # Indexa documento.txt"
echo ""
echo "🧪 PROBAR:"
echo "5. Usa REST Client o curl para llamar /api/rag"
echo ""
echo "📚 DOCUMENTACIÓN:"
echo "  - README.md      # Overview general"
echo "  - SETUP.md       # Setup paso a paso"
echo "  - RESUMEN.md     # Resumen de cambios"
echo ""
echo "🔗 COMANDOS ÚTILES:"
echo ""
echo "npm run db:generate        # Genera migración SQL"
echo "npm run db:push            # Aplica migración a BD"
echo "npm run ingest             # Indexa documentos"
echo ""
echo "📂 ESTRUCTURA:"
echo "data/              - Tus documentos"
echo "scripts/ingest.ts  - Script de ingesta"
echo "src/lib/ai/rag.ts  - Función de búsqueda"
echo "src/app/api/rag/   - Endpoint API"
echo ""
echo "✨ HECHO CON REFERENCIA EN:"
echo "https://aperezl.com/post/rag-dotando-de-memoria-a-tu-agente-parte-1"
echo "https://aperezl.com/post/rag-dotando-de-memoria-a-tu-agente-parte-2"
echo "https://aperezl.com/post/rag-dotando-de-memoria-a-tu-agente-parte-3"
